//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ConnectionStatus.
const (
	Connected    ConnectionStatus = "connected"
	Connecting   ConnectionStatus = "connecting"
	Disconnected ConnectionStatus = "disconnected"
)

// Valid indicates whether the value is a known member of the ConnectionStatus enum.
func (e ConnectionStatus) Valid() bool {
	switch e {
	case Connected:
		return true
	case Connecting:
		return true
	case Disconnected:
		return true
	default:
		return false
	}
}

// Defines values for CreateSessionRequestMode.
const (
	CreateSessionRequestModeSingle CreateSessionRequestMode = "single"
)

// Valid indicates whether the value is a known member of the CreateSessionRequestMode enum.
func (e CreateSessionRequestMode) Valid() bool {
	switch e {
	case CreateSessionRequestModeSingle:
		return true
	default:
		return false
	}
}

// Defines values for EffectMessageName.
const (
	EffectMessageNameConflict EffectMessageName = "conflict"
	EffectMessageNameFall     EffectMessageName = "fall"
	EffectMessageNameFire     EffectMessageName = "fire"
)

// Valid indicates whether the value is a known member of the EffectMessageName enum.
func (e EffectMessageName) Valid() bool {
	switch e {
	case EffectMessageNameConflict:
		return true
	case EffectMessageNameFall:
		return true
	case EffectMessageNameFire:
		return true
	default:
		return false
	}
}

// Defines values for EffectMessageType.
const (
	Effect EffectMessageType = "effect"
)

// Valid indicates whether the value is a known member of the EffectMessageType enum.
func (e EffectMessageType) Valid() bool {
	switch e {
	case Effect:
		return true
	default:
		return false
	}
}

// Defines values for ErrorMessageType.
const (
	ErrorMessageTypeError ErrorMessageType = "error"
)

// Valid indicates whether the value is a known member of the ErrorMessageType enum.
func (e ErrorMessageType) Valid() bool {
	switch e {
	case ErrorMessageTypeError:
		return true
	default:
		return false
	}
}

// Defines values for FileStatus.
const (
	FileStatusEdited        FileStatus = "edited"
	FileStatusFileCreated   FileStatus = "file_created"
	FileStatusImageCreated  FileStatus = "image_created"
	FileStatusSearchCreated FileStatus = "search_created"
	FileStatusUnedited      FileStatus = "unedited"
)

// Valid indicates whether the value is a known member of the FileStatus enum.
func (e FileStatus) Valid() bool {
	switch e {
	case FileStatusEdited:
		return true
	case FileStatusFileCreated:
		return true
	case FileStatusImageCreated:
		return true
	case FileStatusSearchCreated:
		return true
	case FileStatusUnedited:
		return true
	default:
		return false
	}
}

// Defines values for InteractMessageType.
const (
	Interact InteractMessageType = "interact"
)

// Valid indicates whether the value is a known member of the InteractMessageType enum.
func (e InteractMessageType) Valid() bool {
	switch e {
	case Interact:
		return true
	default:
		return false
	}
}

// Defines values for InteractRejectedMessageType.
const (
	ObjectInteractRejected InteractRejectedMessageType = "object.interactRejected"
)

// Valid indicates whether the value is a known member of the InteractRejectedMessageType enum.
func (e InteractRejectedMessageType) Valid() bool {
	switch e {
	case ObjectInteractRejected:
		return true
	default:
		return false
	}
}

// Defines values for ItemKind.
const (
	File    ItemKind = "file"
	Lighter ItemKind = "lighter"
)

// Valid indicates whether the value is a known member of the ItemKind enum.
func (e ItemKind) Valid() bool {
	switch e {
	case File:
		return true
	case Lighter:
		return true
	default:
		return false
	}
}

// Defines values for LifeStatus.
const (
	Alive      LifeStatus = "alive"
	Eliminated LifeStatus = "eliminated"
)

// Valid indicates whether the value is a known member of the LifeStatus enum.
func (e LifeStatus) Valid() bool {
	switch e {
	case Alive:
		return true
	case Eliminated:
		return true
	default:
		return false
	}
}

// Defines values for MatchmakingStatusStatus.
const (
	Matched MatchmakingStatusStatus = "matched"
	Queued  MatchmakingStatusStatus = "queued"
)

// Valid indicates whether the value is a known member of the MatchmakingStatusStatus enum.
func (e MatchmakingStatusStatus) Valid() bool {
	switch e {
	case Matched:
		return true
	case Queued:
		return true
	default:
		return false
	}
}

// Defines values for ObjectAvailability.
const (
	ObjectAvailabilityAvailable   ObjectAvailability = "available"
	ObjectAvailabilityUnavailable ObjectAvailability = "unavailable"
)

// Valid indicates whether the value is a known member of the ObjectAvailability enum.
func (e ObjectAvailability) Valid() bool {
	switch e {
	case ObjectAvailabilityAvailable:
		return true
	case ObjectAvailabilityUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for ObjectKind.
const (
	Canvas       ObjectKind = "canvas"
	Directory    ObjectKind = "directory"
	LighterStand ObjectKind = "lighter_stand"
	Pc           ObjectKind = "pc"
	Workspace    ObjectKind = "workspace"
)

// Valid indicates whether the value is a known member of the ObjectKind enum.
func (e ObjectKind) Valid() bool {
	switch e {
	case Canvas:
		return true
	case Directory:
		return true
	case LighterStand:
		return true
	case Pc:
		return true
	case Workspace:
		return true
	default:
		return false
	}
}

// Defines values for ObjectRemoveMessageType.
const (
	ObjectRemove ObjectRemoveMessageType = "object.remove"
)

// Valid indicates whether the value is a known member of the ObjectRemoveMessageType enum.
func (e ObjectRemoveMessageType) Valid() bool {
	switch e {
	case ObjectRemove:
		return true
	default:
		return false
	}
}

// Defines values for ObjectScope.
const (
	Personal ObjectScope = "personal"
	Shared   ObjectScope = "shared"
)

// Valid indicates whether the value is a known member of the ObjectScope enum.
func (e ObjectScope) Valid() bool {
	switch e {
	case Personal:
		return true
	case Shared:
		return true
	default:
		return false
	}
}

// Defines values for ObjectUpsertMessageType.
const (
	ObjectUpsert ObjectUpsertMessageType = "object.upsert"
)

// Valid indicates whether the value is a known member of the ObjectUpsertMessageType enum.
func (e ObjectUpsertMessageType) Valid() bool {
	switch e {
	case ObjectUpsert:
		return true
	default:
		return false
	}
}

// Defines values for Outcome.
const (
	Defeat  Outcome = "defeat"
	Victory Outcome = "victory"
)

// Valid indicates whether the value is a known member of the Outcome enum.
func (e Outcome) Valid() bool {
	switch e {
	case Defeat:
		return true
	case Victory:
		return true
	default:
		return false
	}
}

// Defines values for PhaseEndedMessageNext.
const (
	PhaseEndedMessageNextCompleted    PhaseEndedMessageNext = "completed"
	PhaseEndedMessageNextIntermission PhaseEndedMessageNext = "intermission"
)

// Valid indicates whether the value is a known member of the PhaseEndedMessageNext enum.
func (e PhaseEndedMessageNext) Valid() bool {
	switch e {
	case PhaseEndedMessageNextCompleted:
		return true
	case PhaseEndedMessageNextIntermission:
		return true
	default:
		return false
	}
}

// Defines values for PhaseEndedMessageType.
const (
	PhaseEnded PhaseEndedMessageType = "phase.ended"
)

// Valid indicates whether the value is a known member of the PhaseEndedMessageType enum.
func (e PhaseEndedMessageType) Valid() bool {
	switch e {
	case PhaseEnded:
		return true
	default:
		return false
	}
}

// Defines values for PhaseStartedMessageType.
const (
	PhaseStarted PhaseStartedMessageType = "phase.started"
)

// Valid indicates whether the value is a known member of the PhaseStartedMessageType enum.
func (e PhaseStartedMessageType) Valid() bool {
	switch e {
	case PhaseStarted:
		return true
	default:
		return false
	}
}

// Defines values for PhaseStatus.
const (
	PhaseStatusActive       PhaseStatus = "active"
	PhaseStatusCompleted    PhaseStatus = "completed"
	PhaseStatusIntermission PhaseStatus = "intermission"
)

// Valid indicates whether the value is a known member of the PhaseStatus enum.
func (e PhaseStatus) Valid() bool {
	switch e {
	case PhaseStatusActive:
		return true
	case PhaseStatusCompleted:
		return true
	case PhaseStatusIntermission:
		return true
	default:
		return false
	}
}

// Defines values for PlayerKind.
const (
	Cpu   PlayerKind = "cpu"
	Human PlayerKind = "human"
)

// Valid indicates whether the value is a known member of the PlayerKind enum.
func (e PlayerKind) Valid() bool {
	switch e {
	case Cpu:
		return true
	case Human:
		return true
	default:
		return false
	}
}

// Defines values for PlayerUpdatedMessageType.
const (
	PlayerUpdated PlayerUpdatedMessageType = "player.updated"
)

// Valid indicates whether the value is a known member of the PlayerUpdatedMessageType enum.
func (e PlayerUpdatedMessageType) Valid() bool {
	switch e {
	case PlayerUpdated:
		return true
	default:
		return false
	}
}

// Defines values for RejectReason.
const (
	RejectReasonMissingItem RejectReason = "missing_item"
	RejectReasonNotFound    RejectReason = "not_found"
	RejectReasonNotOwner    RejectReason = "not_owner"
	RejectReasonTooFar      RejectReason = "too_far"
	RejectReasonUnavailable RejectReason = "unavailable"
)

// Valid indicates whether the value is a known member of the RejectReason enum.
func (e RejectReason) Valid() bool {
	switch e {
	case RejectReasonMissingItem:
		return true
	case RejectReasonNotFound:
		return true
	case RejectReasonNotOwner:
		return true
	case RejectReasonTooFar:
		return true
	case RejectReasonUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for SessionFinishedMessageType.
const (
	SessionFinished SessionFinishedMessageType = "session.finished"
)

// Valid indicates whether the value is a known member of the SessionFinishedMessageType enum.
func (e SessionFinishedMessageType) Valid() bool {
	switch e {
	case SessionFinished:
		return true
	default:
		return false
	}
}

// Defines values for SessionMode.
const (
	SessionModeMultiplayer SessionMode = "multiplayer"
	SessionModeSingle      SessionMode = "single"
)

// Valid indicates whether the value is a known member of the SessionMode enum.
func (e SessionMode) Valid() bool {
	switch e {
	case SessionModeMultiplayer:
		return true
	case SessionModeSingle:
		return true
	default:
		return false
	}
}

// Defines values for SessionSnapshotSchemaVersion.
const (
	N2 SessionSnapshotSchemaVersion = 2
)

// Valid indicates whether the value is a known member of the SessionSnapshotSchemaVersion enum.
func (e SessionSnapshotSchemaVersion) Valid() bool {
	switch e {
	case N2:
		return true
	default:
		return false
	}
}

// Defines values for SessionStartedMessageType.
const (
	SessionStarted SessionStartedMessageType = "session.started"
)

// Valid indicates whether the value is a known member of the SessionStartedMessageType enum.
func (e SessionStartedMessageType) Valid() bool {
	switch e {
	case SessionStarted:
		return true
	default:
		return false
	}
}

// Defines values for SessionStatus.
const (
	SessionStatusFinished     SessionStatus = "finished"
	SessionStatusIntermission SessionStatus = "intermission"
	SessionStatusPlaying      SessionStatus = "playing"
	SessionStatusWaiting      SessionStatus = "waiting"
)

// Valid indicates whether the value is a known member of the SessionStatus enum.
func (e SessionStatus) Valid() bool {
	switch e {
	case SessionStatusFinished:
		return true
	case SessionStatusIntermission:
		return true
	case SessionStatusPlaying:
		return true
	case SessionStatusWaiting:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotMessageType.
const (
	Snapshot SnapshotMessageType = "snapshot"
)

// Valid indicates whether the value is a known member of the SnapshotMessageType enum.
func (e SnapshotMessageType) Valid() bool {
	switch e {
	case Snapshot:
		return true
	default:
		return false
	}
}

// Defines values for StockFileStatus.
const (
	StockFileStatusEdited   StockFileStatus = "edited"
	StockFileStatusUnedited StockFileStatus = "unedited"
)

// Valid indicates whether the value is a known member of the StockFileStatus enum.
func (e StockFileStatus) Valid() bool {
	switch e {
	case StockFileStatusEdited:
		return true
	case StockFileStatusUnedited:
		return true
	default:
		return false
	}
}

// Defines values for TaskCompletedMessageType.
const (
	TaskCompleted TaskCompletedMessageType = "task.completed"
)

// Valid indicates whether the value is a known member of the TaskCompletedMessageType enum.
func (e TaskCompletedMessageType) Valid() bool {
	switch e {
	case TaskCompleted:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatus.
const (
	TaskStatusCompleted TaskStatus = "completed"
	TaskStatusPending   TaskStatus = "pending"
)

// Valid indicates whether the value is a known member of the TaskStatus enum.
func (e TaskStatus) Valid() bool {
	switch e {
	case TaskStatusCompleted:
		return true
	case TaskStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for TaskType.
const (
	ImageGeneration TaskType = "image_generation"
	ReadEdit        TaskType = "read_edit"
	WebSearch       TaskType = "web_search"
	Write           TaskType = "write"
)

// Valid indicates whether the value is a known member of the TaskType enum.
func (e TaskType) Valid() bool {
	switch e {
	case ImageGeneration:
		return true
	case ReadEdit:
		return true
	case WebSearch:
		return true
	case Write:
		return true
	default:
		return false
	}
}

// Defines values for TeamUpdatedMessageType.
const (
	TeamUpdated TeamUpdatedMessageType = "team.updated"
)

// Valid indicates whether the value is a known member of the TeamUpdatedMessageType enum.
func (e TeamUpdatedMessageType) Valid() bool {
	switch e {
	case TeamUpdated:
		return true
	default:
		return false
	}
}

// Defines values for TransformMessageType.
const (
	TransformMessageTypeTransform TransformMessageType = "transform"
)

// Valid indicates whether the value is a known member of the TransformMessageType enum.
func (e TransformMessageType) Valid() bool {
	switch e {
	case TransformMessageTypeTransform:
		return true
	default:
		return false
	}
}

// Defines values for TransformsMessageType.
const (
	Transforms TransformsMessageType = "transforms"
)

// Valid indicates whether the value is a known member of the TransformsMessageType enum.
func (e TransformsMessageType) Valid() bool {
	switch e {
	case Transforms:
		return true
	default:
		return false
	}
}

// Defines values for GetHealth200JSONResponseBodyStatus.
const (
	Ok GetHealth200JSONResponseBodyStatus = "ok"
)

// Valid indicates whether the value is a known member of the GetHealth200JSONResponseBodyStatus enum.
func (e GetHealth200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// ClientMessage defines model for ClientMessage.
type ClientMessage struct {
	union json.RawMessage
}

// ConnectionStatus defines model for ConnectionStatus.
type ConnectionStatus string

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	Mode CreateSessionRequestMode `json:"mode"`
}

// CreateSessionRequestMode defines model for CreateSessionRequest.Mode.
type CreateSessionRequestMode string

// DirectoryData defines model for DirectoryData.
type DirectoryData struct {
	// Outputs このフェーズで入れられた成果物(新しく作ったファイル)の数
	Outputs int `json:"outputs"`

	// Stock 今ディレクトリの中にある在庫のファイル(誰かが持っている間は含まれない)
	Stock []StockFile `json:"stock"`
}

// EffectMessage 一時的な演出。確定状態ではなく、再接続時に再生しない。seq を持たない
type EffectMessage struct {
	Name     EffectMessageName `json:"name"`
	ObjectId *string           `json:"objectId,omitempty"`

	// PlayerId Example: p1
	PlayerId *PlayerId         `json:"playerId,omitempty"`
	Type     EffectMessageType `json:"type"`
}

// EffectMessageName defines model for EffectMessage.Name.
type EffectMessageName string

// EffectMessageType defines model for EffectMessage.Type.
type EffectMessageType string

// Error defines model for Error.
type Error struct {
	// Code Example: not_found
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ErrorMessage 不正なメッセージなど。本人にだけ送る
type ErrorMessage struct {
	Code    string           `json:"code"`
	Message string           `json:"message"`
	Type    ErrorMessageType `json:"type"`
}

// ErrorMessageType defines model for ErrorMessage.Type.
type ErrorMessageType string

// FileItemData defines model for FileItemData.
type FileItemData struct {
	// Color アウトラインの色。在庫から取り出したファイルだけ持つ
	//
	// Example: #ffd60a
	Color *string `json:"color,omitempty"`

	// Status ファイルの状態。unedited / edited はディレクトリの在庫から取り出したもの。
	// file_created / search_created / image_created は新しく作ったもの(編集はしない)
	Status FileStatus `json:"status"`
}

// FileStatus ファイルの状態。unedited / edited はディレクトリの在庫から取り出したもの。
// file_created / search_created / image_created は新しく作ったもの(編集はしない)
type FileStatus string

// Game defines model for Game.
type Game struct {
	// Phase 開始前は null
	Phase *Phase `json:"phase"`

	// Result 決着前は null
	Result *Result `json:"result"`

	// Team チーム共有の勝利条件フラグ
	Team Team `json:"team"`
}

// GameObject ワールドに置かれた、機能を持つ物体
type GameObject struct {
	Availability ObjectAvailability `json:"availability"`

	// Data kind が directory なら DirectoryData。他は未定(null)
	Data JsonValue `json:"data"`

	// Id Example: directory-1
	Id string `json:"id"`

	// Kind directory 以外は暫定の名前
	Kind ObjectKind `json:"kind"`

	// Owner scope が personal のときだけ
	Owner *PlayerId `json:"owner,omitempty"`

	// Position [x, y, z]。ワールド座標(Y-up)
	//
	// Example: [1.25,0,-2.5]
	Position Vec3 `json:"position"`

	// Scope personal は各プレイヤーの区画のもの。shared は全員共通(ディレクトリだけ)
	Scope ObjectScope `json:"scope"`

	// Users 今触っているプレイヤー。personal は最大 1 人、shared は複数人
	Users []PlayerId `json:"users"`
}

// HeldItemRef インタラクト時の手持ちの主張。識別に足りる分だけ
type HeldItemRef struct {
	Id   string   `json:"id"`
	Kind ItemKind `json:"kind"`
}

// InteractMessage オブジェクトへの操作の要求。送信者は接続から決まる
type InteractMessage struct {
	// HeldItem 手持ちの主張(サーバーは実際の手持ちで判定する)。手ぶらなら null
	HeldItem *HeldItemRef `json:"heldItem"`
	ObjectId string       `json:"objectId"`

	// Target 対象の中から 1 つ選ぶときの指定(例: 取り出すファイルの id)
	Target *string             `json:"target,omitempty"`
	Type   InteractMessageType `json:"type"`
}

// InteractMessageType defines model for InteractMessage.Type.
type InteractMessageType string

// InteractRejectedMessage 要求した本人にだけ送る。画面上は何も起きない。seq を持たない
type InteractRejectedMessage struct {
	ObjectId string                      `json:"objectId"`
	Reason   RejectReason                `json:"reason"`
	Type     InteractRejectedMessageType `json:"type"`
}

// InteractRejectedMessageType defines model for InteractRejectedMessage.Type.
type InteractRejectedMessageType string

// Item 手に持つ物。手は 1 つなので、プレイヤーが持てるのは 1 個
type Item struct {
	// Data kind が file なら FileItemData、lighter なら null
	Data JsonValue `json:"data"`

	// Id Example: file-02
	Id   string   `json:"id"`
	Kind ItemKind `json:"kind"`
}

// ItemKind defines model for ItemKind.
type ItemKind string

// JsonValue kind ごとに中身が決まる自由な JSON(null を含む何でも)
type JsonValue = interface{}

// LifeStatus defines model for LifeStatus.
type LifeStatus string

// MatchmakingStatus defines model for MatchmakingStatus.
type MatchmakingStatus struct {
	QueuedAt time.Time `json:"queuedAt"`

	// SessionId status が matched のときだけ
	SessionId *string                 `json:"sessionId,omitempty"`
	Status    MatchmakingStatusStatus `json:"status"`
}

// MatchmakingStatusStatus defines model for MatchmakingStatus.Status.
type MatchmakingStatusStatus string

// Me defines model for Me.
type Me struct {
	// PlayerId Example: p1
	PlayerId PlayerId `json:"playerId"`

	// SessionId 参加中のセッション。無ければ null
	SessionId *string `json:"sessionId"`
}

// ObjectAvailability defines model for ObjectAvailability.
type ObjectAvailability string

// ObjectKind directory 以外は暫定の名前
type ObjectKind string

// ObjectRemoveMessage defines model for ObjectRemoveMessage.
type ObjectRemoveMessage struct {
	Id string `json:"id"`

	// Seq セッション内の確定状態の更新順序。単調に増える
	Seq  Seq                     `json:"seq"`
	Type ObjectRemoveMessageType `json:"type"`
}

// ObjectRemoveMessageType defines model for ObjectRemoveMessage.Type.
type ObjectRemoveMessageType string

// ObjectScope personal は各プレイヤーの区画のもの。shared は全員共通(ディレクトリだけ)
type ObjectScope string

// ObjectUpsertMessage defines model for ObjectUpsertMessage.
type ObjectUpsertMessage struct {
	// Object ワールドに置かれた、機能を持つ物体
	Object GameObject `json:"object"`

	// Seq セッション内の確定状態の更新順序。単調に増える
	Seq  Seq                     `json:"seq"`
	Type ObjectUpsertMessageType `json:"type"`
}

// ObjectUpsertMessageType defines model for ObjectUpsertMessage.Type.
type ObjectUpsertMessageType string

// Outcome defines model for Outcome.
type Outcome string

// Phase defines model for Phase.
type Phase struct {
	// DeadlineAt 残り時間はこれと serverTime から算出する
	DeadlineAt time.Time   `json:"deadlineAt"`
	Number     int         `json:"number"`
	StartedAt  time.Time   `json:"startedAt"`
	Status     PhaseStatus `json:"status"`
	Tasks      []Task      `json:"tasks"`
}

// PhaseEndedMessage defines model for PhaseEndedMessage.
type PhaseEndedMessage struct {
	// EliminatedPlayerIds このフェーズの締切で脱落したプレイヤー
	EliminatedPlayerIds []PlayerId `json:"eliminatedPlayerIds"`

	// Next intermission なら次のフェーズがある。completed なら最後のフェーズだった
	Next        PhaseEndedMessageNext `json:"next"`
	PhaseNumber int                   `json:"phaseNumber"`

	// Seq セッション内の確定状態の更新順序。単調に増える
	Seq  Seq                   `json:"seq"`
	Type PhaseEndedMessageType `json:"type"`
}

// PhaseEndedMessageNext intermission なら次のフェーズがある。completed なら最後のフェーズだった
type PhaseEndedMessageNext string

// PhaseEndedMessageType defines model for PhaseEndedMessage.Type.
type PhaseEndedMessageType string

// PhaseStartedMessage defines model for PhaseStartedMessage.
type PhaseStartedMessage struct {
	Phase Phase `json:"phase"`

	// Seq セッション内の確定状態の更新順序。単調に増える
	Seq        Seq                     `json:"seq"`
	ServerTime time.Time               `json:"serverTime"`
	Type       PhaseStartedMessageType `json:"type"`
}

// PhaseStartedMessageType defines model for PhaseStartedMessage.Type.
type PhaseStartedMessageType string

// PhaseStatus defines model for PhaseStatus.
type PhaseStatus string

// Player defines model for Player.
type Player struct {
	Connection ConnectionStatus `json:"connection"`
	HeldItem   *Item            `json:"heldItem"`
	Kind       PlayerKind       `json:"kind"`
	Life       LifeStatus       `json:"life"`

	// PlayerId Example: p1
	PlayerId PlayerId `json:"playerId"`

	// Seat サンドボックスの区画の番号
	Seat      int       `json:"seat"`
	Transform Transform `json:"transform"`
}

// PlayerId Example: p1
type PlayerId = string

// PlayerKind defines model for PlayerKind.
type PlayerKind string

// PlayerStatus transform を除くプレイヤー情報(player.updated で配る)
type PlayerStatus struct {
	Connection ConnectionStatus `json:"connection"`
	HeldItem   *Item            `json:"heldItem"`
	Kind       PlayerKind       `json:"kind"`
	Life       LifeStatus       `json:"life"`

	// PlayerId Example: p1
	PlayerId PlayerId `json:"playerId"`

	// Seat サンドボックスの区画の番号
	Seat int `json:"seat"`
}

// PlayerUpdatedMessage 接続状態・生死・手持ちの変化
type PlayerUpdatedMessage struct {
	// Player transform を除くプレイヤー情報(player.updated で配る)
	Player PlayerStatus `json:"player"`

	// Seq セッション内の確定状態の更新順序。単調に増える
	Seq  Seq                      `json:"seq"`
	Type PlayerUpdatedMessageType `json:"type"`
}

// PlayerUpdatedMessageType defines model for PlayerUpdatedMessage.Type.
type PlayerUpdatedMessageType string

// RejectReason defines model for RejectReason.
type RejectReason string

// Result defines model for Result.
type Result struct {
	DecidedAt time.Time `json:"decidedAt"`
	Outcome   Outcome   `json:"outcome"`
}

// Seq セッション内の確定状態の更新順序。単調に増える
type Seq = int64

// ServerMessage defines model for ServerMessage.
type ServerMessage struct {
	union json.RawMessage
}

// SessionFinishedMessage defines model for SessionFinishedMessage.
type SessionFinishedMessage struct {
	Result Result `json:"result"`

	// Seq セッション内の確定状態の更新順序。単調に増える
	Seq  Seq                        `json:"seq"`
	Type SessionFinishedMessageType `json:"type"`
}

// SessionFinishedMessageType defines model for SessionFinishedMessage.Type.
type SessionFinishedMessageType string

// SessionId Example: sess-abc123
type SessionId = string

// SessionMode defines model for SessionMode.
type SessionMode string

// SessionSnapshot defines model for SessionSnapshot.
type SessionSnapshot struct {
	CreatedAt     time.Time                    `json:"createdAt"`
	Game          Game                         `json:"game"`
	Mode          SessionMode                  `json:"mode"`
	Objects       []GameObject                 `json:"objects"`
	Players       []Player                     `json:"players"`
	SchemaVersion SessionSnapshotSchemaVersion `json:"schemaVersion"`

	// Seq セッション内の確定状態の更新順序。単調に増える
	Seq Seq `json:"seq"`

	// ServerTime 送信時のサーバー時刻。クライアントは時計のずれの補正に使う
	ServerTime time.Time `json:"serverTime"`

	// SessionId Example: sess-abc123
	SessionId SessionId     `json:"sessionId"`
	Status    SessionStatus `json:"status"`
}

// SessionSnapshotSchemaVersion defines model for SessionSnapshot.SchemaVersion.
type SessionSnapshotSchemaVersion int

// SessionStartedMessage defines model for SessionStartedMessage.
type SessionStartedMessage struct {
	// Seq セッション内の確定状態の更新順序。単調に増える
	Seq       Seq                       `json:"seq"`
	StartedAt time.Time                 `json:"startedAt"`
	Type      SessionStartedMessageType `json:"type"`
}

// SessionStartedMessageType defines model for SessionStartedMessage.Type.
type SessionStartedMessageType string

// SessionStatus defines model for SessionStatus.
type SessionStatus string

// SnapshotMessage 接続・再接続した本人に、最初に送る
type SnapshotMessage struct {
	Session SessionSnapshot     `json:"session"`
	Type    SnapshotMessageType `json:"type"`
}

// SnapshotMessageType defines model for SnapshotMessage.Type.
type SnapshotMessageType string

// StockFile defines model for StockFile.
type StockFile struct {
	Color string `json:"color"`
	Id    string `json:"id"`

	// Status 在庫のファイルの状態(編集前か編集済みか)
	Status StockFileStatus `json:"status"`
}

// StockFileStatus 在庫のファイルの状態(編集前か編集済みか)
type StockFileStatus string

// Task defines model for Task.
type Task struct {
	// AssigneePlayerId Example: p1
	AssigneePlayerId PlayerId `json:"assigneePlayerId"`

	// CompletedAt サーバーが完了を受け付けた時刻
	CompletedAt *time.Time `json:"completedAt"`
	Status      TaskStatus `json:"status"`

	// TargetFileId read_edit のときだけ。対象の在庫ファイルの id
	TargetFileId *string  `json:"targetFileId"`
	TaskId       string   `json:"taskId"`
	Type         TaskType `json:"type"`
}

// TaskCompletedMessage defines model for TaskCompletedMessage.
type TaskCompletedMessage struct {
	CompletedAt time.Time `json:"completedAt"`

	// Seq セッション内の確定状態の更新順序。単調に増える
	Seq    Seq                      `json:"seq"`
	TaskId string                   `json:"taskId"`
	Type   TaskCompletedMessageType `json:"type"`
}

// TaskCompletedMessageType defines model for TaskCompletedMessage.Type.
type TaskCompletedMessageType string

// TaskStatus defines model for TaskStatus.
type TaskStatus string

// TaskType defines model for TaskType.
type TaskType string

// Team チーム共有の勝利条件フラグ
type Team struct {
	BypassPermission bool `json:"bypassPermission"`
	FireStarted      bool `json:"fireStarted"`
}

// TeamUpdatedMessage defines model for TeamUpdatedMessage.
type TeamUpdatedMessage struct {
	// Seq セッション内の確定状態の更新順序。単調に増える
	Seq Seq `json:"seq"`

	// Team チーム共有の勝利条件フラグ
	Team Team                   `json:"team"`
	Type TeamUpdatedMessageType `json:"type"`
}

// TeamUpdatedMessageType defines model for TeamUpdatedMessage.Type.
type TeamUpdatedMessageType string

// Transform defines model for Transform.
type Transform struct {
	// Pitch ラジアン。上向きが正
	Pitch float64 `json:"pitch"`

	// Position 足元の位置
	Position Vec3 `json:"position"`

	// Seq そのプレイヤーの更新ごとに増やす。増えない更新は捨てる
	Seq int64 `json:"seq"`

	// Yaw ラジアン。0 で -Z を向く
	Yaw float64 `json:"yaw"`
}

// TransformMessage 自分の位置と向き。20Hz で送る(止まっている間は送らなくてよい)
type TransformMessage struct {
	Pitch float64 `json:"pitch"`

	// Position [x, y, z]。ワールド座標(Y-up)
	//
	// Example: [1.25,0,-2.5]
	Position Vec3                 `json:"position"`
	Seq      int64                `json:"seq"`
	Type     TransformMessageType `json:"type"`
	Yaw      float64              `json:"yaw"`
}

// TransformMessageType defines model for TransformMessage.Type.
type TransformMessageType string

// TransformsMessage 前回の配信から動いたプレイヤーの位置と向き。最大 20Hz で全員に送り、誰も動いていなければ送らない。seq を持たない
type TransformsMessage struct {
	Players []struct {
		// PlayerId Example: p1
		PlayerId  PlayerId  `json:"playerId"`
		Transform Transform `json:"transform"`
	} `json:"players"`
	ServerTime time.Time             `json:"serverTime"`
	Type       TransformsMessageType `json:"type"`
}

// TransformsMessageType defines model for TransformsMessage.Type.
type TransformsMessageType string

// Vec3 [x, y, z]。ワールド座標(Y-up)
//
// Example: [1.25,0,-2.5]
type Vec3 = []float64

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GetHealth200JSONResponseBodyStatus defines parameters for GetHealth.
type GetHealth200JSONResponseBodyStatus string

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// AsTransformMessage returns the union data inside the ClientMessage as a TransformMessage
func (t ClientMessage) AsTransformMessage() (TransformMessage, error) {
	var body TransformMessage
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTransformMessage overwrites any union data inside the ClientMessage as the provided TransformMessage
func (t *ClientMessage) FromTransformMessage(v TransformMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"transform"}`))
	t.union = b
	return err
}

// MergeTransformMessage performs a merge with any union data inside the ClientMessage, using the provided TransformMessage
func (t *ClientMessage) MergeTransformMessage(v TransformMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"transform"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInteractMessage returns the union data inside the ClientMessage as a InteractMessage
func (t ClientMessage) AsInteractMessage() (InteractMessage, error) {
	var body InteractMessage
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInteractMessage overwrites any union data inside the ClientMessage as the provided InteractMessage
func (t *ClientMessage) FromInteractMessage(v InteractMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"interact"}`))
	t.union = b
	return err
}

// MergeInteractMessage performs a merge with any union data inside the ClientMessage, using the provided InteractMessage
func (t *ClientMessage) MergeInteractMessage(v InteractMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"interact"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ClientMessage) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ClientMessage) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "interact":
		return t.AsInteractMessage()
	case "transform":
		return t.AsTransformMessage()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ClientMessage) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ClientMessage) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSnapshotMessage returns the union data inside the ServerMessage as a SnapshotMessage
func (t ServerMessage) AsSnapshotMessage() (SnapshotMessage, error) {
	var body SnapshotMessage
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSnapshotMessage overwrites any union data inside the ServerMessage as the provided SnapshotMessage
func (t *ServerMessage) FromSnapshotMessage(v SnapshotMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"snapshot"}`))
	t.union = b
	return err
}

// MergeSnapshotMessage performs a merge with any union data inside the ServerMessage, using the provided SnapshotMessage
func (t *ServerMessage) MergeSnapshotMessage(v SnapshotMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"snapshot"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTransformsMessage returns the union data inside the ServerMessage as a TransformsMessage
func (t ServerMessage) AsTransformsMessage() (TransformsMessage, error) {
	var body TransformsMessage
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTransformsMessage overwrites any union data inside the ServerMessage as the provided TransformsMessage
func (t *ServerMessage) FromTransformsMessage(v TransformsMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"transforms"}`))
	t.union = b
	return err
}

// MergeTransformsMessage performs a merge with any union data inside the ServerMessage, using the provided TransformsMessage
func (t *ServerMessage) MergeTransformsMessage(v TransformsMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"transforms"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSessionStartedMessage returns the union data inside the ServerMessage as a SessionStartedMessage
func (t ServerMessage) AsSessionStartedMessage() (SessionStartedMessage, error) {
	var body SessionStartedMessage
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSessionStartedMessage overwrites any union data inside the ServerMessage as the provided SessionStartedMessage
func (t *ServerMessage) FromSessionStartedMessage(v SessionStartedMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"session.started"}`))
	t.union = b
	return err
}

// MergeSessionStartedMessage performs a merge with any union data inside the ServerMessage, using the provided SessionStartedMessage
func (t *ServerMessage) MergeSessionStartedMessage(v SessionStartedMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"session.started"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSessionFinishedMessage returns the union data inside the ServerMessage as a SessionFinishedMessage
func (t ServerMessage) AsSessionFinishedMessage() (SessionFinishedMessage, error) {
	var body SessionFinishedMessage
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSessionFinishedMessage overwrites any union data inside the ServerMessage as the provided SessionFinishedMessage
func (t *ServerMessage) FromSessionFinishedMessage(v SessionFinishedMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"session.finished"}`))
	t.union = b
	return err
}

// MergeSessionFinishedMessage performs a merge with any union data inside the ServerMessage, using the provided SessionFinishedMessage
func (t *ServerMessage) MergeSessionFinishedMessage(v SessionFinishedMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"session.finished"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPhaseStartedMessage returns the union data inside the ServerMessage as a PhaseStartedMessage
func (t ServerMessage) AsPhaseStartedMessage() (PhaseStartedMessage, error) {
	var body PhaseStartedMessage
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPhaseStartedMessage overwrites any union data inside the ServerMessage as the provided PhaseStartedMessage
func (t *ServerMessage) FromPhaseStartedMessage(v PhaseStartedMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"phase.started"}`))
	t.union = b
	return err
}

// MergePhaseStartedMessage performs a merge with any union data inside the ServerMessage, using the provided PhaseStartedMessage
func (t *ServerMessage) MergePhaseStartedMessage(v PhaseStartedMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"phase.started"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPhaseEndedMessage returns the union data inside the ServerMessage as a PhaseEndedMessage
func (t ServerMessage) AsPhaseEndedMessage() (PhaseEndedMessage, error) {
	var body PhaseEndedMessage
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPhaseEndedMessage overwrites any union data inside the ServerMessage as the provided PhaseEndedMessage
func (t *ServerMessage) FromPhaseEndedMessage(v PhaseEndedMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"phase.ended"}`))
	t.union = b
	return err
}

// MergePhaseEndedMessage performs a merge with any union data inside the ServerMessage, using the provided PhaseEndedMessage
func (t *ServerMessage) MergePhaseEndedMessage(v PhaseEndedMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"phase.ended"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTaskCompletedMessage returns the union data inside the ServerMessage as a TaskCompletedMessage
func (t ServerMessage) AsTaskCompletedMessage() (TaskCompletedMessage, error) {
	var body TaskCompletedMessage
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTaskCompletedMessage overwrites any union data inside the ServerMessage as the provided TaskCompletedMessage
func (t *ServerMessage) FromTaskCompletedMessage(v TaskCompletedMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"task.completed"}`))
	t.union = b
	return err
}

// MergeTaskCompletedMessage performs a merge with any union data inside the ServerMessage, using the provided TaskCompletedMessage
func (t *ServerMessage) MergeTaskCompletedMessage(v TaskCompletedMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"task.completed"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsObjectUpsertMessage returns the union data inside the ServerMessage as a ObjectUpsertMessage
func (t ServerMessage) AsObjectUpsertMessage() (ObjectUpsertMessage, error) {
	var body ObjectUpsertMessage
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromObjectUpsertMessage overwrites any union data inside the ServerMessage as the provided ObjectUpsertMessage
func (t *ServerMessage) FromObjectUpsertMessage(v ObjectUpsertMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"object.upsert"}`))
	t.union = b
	return err
}

// MergeObjectUpsertMessage performs a merge with any union data inside the ServerMessage, using the provided ObjectUpsertMessage
func (t *ServerMessage) MergeObjectUpsertMessage(v ObjectUpsertMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"object.upsert"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsObjectRemoveMessage returns the union data inside the ServerMessage as a ObjectRemoveMessage
func (t ServerMessage) AsObjectRemoveMessage() (ObjectRemoveMessage, error) {
	var body ObjectRemoveMessage
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromObjectRemoveMessage overwrites any union data inside the ServerMessage as the provided ObjectRemoveMessage
func (t *ServerMessage) FromObjectRemoveMessage(v ObjectRemoveMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"object.remove"}`))
	t.union = b
	return err
}

// MergeObjectRemoveMessage performs a merge with any union data inside the ServerMessage, using the provided ObjectRemoveMessage
func (t *ServerMessage) MergeObjectRemoveMessage(v ObjectRemoveMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"object.remove"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInteractRejectedMessage returns the union data inside the ServerMessage as a InteractRejectedMessage
func (t ServerMessage) AsInteractRejectedMessage() (InteractRejectedMessage, error) {
	var body InteractRejectedMessage
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInteractRejectedMessage overwrites any union data inside the ServerMessage as the provided InteractRejectedMessage
func (t *ServerMessage) FromInteractRejectedMessage(v InteractRejectedMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"object.interactRejected"}`))
	t.union = b
	return err
}

// MergeInteractRejectedMessage performs a merge with any union data inside the ServerMessage, using the provided InteractRejectedMessage
func (t *ServerMessage) MergeInteractRejectedMessage(v InteractRejectedMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"object.interactRejected"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPlayerUpdatedMessage returns the union data inside the ServerMessage as a PlayerUpdatedMessage
func (t ServerMessage) AsPlayerUpdatedMessage() (PlayerUpdatedMessage, error) {
	var body PlayerUpdatedMessage
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPlayerUpdatedMessage overwrites any union data inside the ServerMessage as the provided PlayerUpdatedMessage
func (t *ServerMessage) FromPlayerUpdatedMessage(v PlayerUpdatedMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"player.updated"}`))
	t.union = b
	return err
}

// MergePlayerUpdatedMessage performs a merge with any union data inside the ServerMessage, using the provided PlayerUpdatedMessage
func (t *ServerMessage) MergePlayerUpdatedMessage(v PlayerUpdatedMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"player.updated"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTeamUpdatedMessage returns the union data inside the ServerMessage as a TeamUpdatedMessage
func (t ServerMessage) AsTeamUpdatedMessage() (TeamUpdatedMessage, error) {
	var body TeamUpdatedMessage
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTeamUpdatedMessage overwrites any union data inside the ServerMessage as the provided TeamUpdatedMessage
func (t *ServerMessage) FromTeamUpdatedMessage(v TeamUpdatedMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"team.updated"}`))
	t.union = b
	return err
}

// MergeTeamUpdatedMessage performs a merge with any union data inside the ServerMessage, using the provided TeamUpdatedMessage
func (t *ServerMessage) MergeTeamUpdatedMessage(v TeamUpdatedMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"team.updated"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEffectMessage returns the union data inside the ServerMessage as a EffectMessage
func (t ServerMessage) AsEffectMessage() (EffectMessage, error) {
	var body EffectMessage
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEffectMessage overwrites any union data inside the ServerMessage as the provided EffectMessage
func (t *ServerMessage) FromEffectMessage(v EffectMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"effect"}`))
	t.union = b
	return err
}

// MergeEffectMessage performs a merge with any union data inside the ServerMessage, using the provided EffectMessage
func (t *ServerMessage) MergeEffectMessage(v EffectMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"effect"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsErrorMessage returns the union data inside the ServerMessage as a ErrorMessage
func (t ServerMessage) AsErrorMessage() (ErrorMessage, error) {
	var body ErrorMessage
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorMessage overwrites any union data inside the ServerMessage as the provided ErrorMessage
func (t *ServerMessage) FromErrorMessage(v ErrorMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"error"}`))
	t.union = b
	return err
}

// MergeErrorMessage performs a merge with any union data inside the ServerMessage, using the provided ErrorMessage
func (t *ServerMessage) MergeErrorMessage(v ErrorMessage) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"error"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ServerMessage) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ServerMessage) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "effect":
		return t.AsEffectMessage()
	case "error":
		return t.AsErrorMessage()
	case "object.interactRejected":
		return t.AsInteractRejectedMessage()
	case "object.remove":
		return t.AsObjectRemoveMessage()
	case "object.upsert":
		return t.AsObjectUpsertMessage()
	case "phase.ended":
		return t.AsPhaseEndedMessage()
	case "phase.started":
		return t.AsPhaseStartedMessage()
	case "player.updated":
		return t.AsPlayerUpdatedMessage()
	case "session.finished":
		return t.AsSessionFinishedMessage()
	case "session.started":
		return t.AsSessionStartedMessage()
	case "snapshot":
		return t.AsSnapshotMessage()
	case "task.completed":
		return t.AsTaskCompletedMessage()
	case "team.updated":
		return t.AsTeamUpdatedMessage()
	case "transforms":
		return t.AsTransformsMessage()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ServerMessage) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ServerMessage) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// LeaveMatchmaking 待機をやめる
	// (DELETE /api/v1/matchmaking)
	LeaveMatchmaking(w http.ResponseWriter, r *http.Request)
	// GetMatchmaking 自分のマッチング状況(ポーリング用)
	// (GET /api/v1/matchmaking)
	GetMatchmaking(w http.ResponseWriter, r *http.Request)
	// JoinMatchmaking 自動マッチングの待機列に入る
	// (POST /api/v1/matchmaking)
	JoinMatchmaking(w http.ResponseWriter, r *http.Request)
	// CreatePlayer 匿名プレイヤーを作り、Cookie を発行する
	// (POST /api/v1/players)
	CreatePlayer(w http.ResponseWriter, r *http.Request)
	// GetMe 自分の ID と、参加中のセッション
	// (GET /api/v1/players/me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// CreateSession シングルモードのセッションを作る
	// (POST /api/v1/sessions)
	CreateSession(w http.ResponseWriter, r *http.Request)
	// GetSession セッションのスナップショット(参加者のみ)
	// (GET /api/v1/sessions/{sessionId})
	GetSession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// ConnectSession WebSocket に切り替える(参加者のみ)
	// (GET /api/v1/sessions/{sessionId}/ws)
	ConnectSession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// GetHealth ヘルスチェック
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// LeaveMatchmaking operation middleware
func (siw *ServerInterfaceWrapper) LeaveMatchmaking(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LeaveMatchmaking(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMatchmaking operation middleware
func (siw *ServerInterfaceWrapper) GetMatchmaking(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMatchmaking(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// JoinMatchmaking operation middleware
func (siw *ServerInterfaceWrapper) JoinMatchmaking(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.JoinMatchmaking(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePlayer operation middleware
func (siw *ServerInterfaceWrapper) CreatePlayer(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePlayer(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConnectSession operation middleware
func (siw *ServerInterfaceWrapper) ConnectSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConnectSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/players", wrapper.CreatePlayer)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/players/me", wrapper.GetMe)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/matchmaking", wrapper.LeaveMatchmaking)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/matchmaking", wrapper.GetMatchmaking)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/matchmaking", wrapper.JoinMatchmaking)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/sessions", wrapper.CreateSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/sessions/{sessionId}", wrapper.GetSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/sessions/{sessionId}/ws", wrapper.ConnectSession)

	return m
}
