//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ConnectionStatus.
const (
	Connected    ConnectionStatus = "connected"
	Connecting   ConnectionStatus = "connecting"
	Disconnected ConnectionStatus = "disconnected"
)

// Valid indicates whether the value is a known member of the ConnectionStatus enum.
func (e ConnectionStatus) Valid() bool {
	switch e {
	case Connected:
		return true
	case Connecting:
		return true
	case Disconnected:
		return true
	default:
		return false
	}
}

// Defines values for CreateSessionRequestMode.
const (
	CreateSessionRequestModeSingle CreateSessionRequestMode = "single"
)

// Valid indicates whether the value is a known member of the CreateSessionRequestMode enum.
func (e CreateSessionRequestMode) Valid() bool {
	switch e {
	case CreateSessionRequestModeSingle:
		return true
	default:
		return false
	}
}

// Defines values for ItemKind.
const (
	File    ItemKind = "file"
	Lighter ItemKind = "lighter"
)

// Valid indicates whether the value is a known member of the ItemKind enum.
func (e ItemKind) Valid() bool {
	switch e {
	case File:
		return true
	case Lighter:
		return true
	default:
		return false
	}
}

// Defines values for LifeStatus.
const (
	Alive      LifeStatus = "alive"
	Eliminated LifeStatus = "eliminated"
)

// Valid indicates whether the value is a known member of the LifeStatus enum.
func (e LifeStatus) Valid() bool {
	switch e {
	case Alive:
		return true
	case Eliminated:
		return true
	default:
		return false
	}
}

// Defines values for MatchmakingStatusStatus.
const (
	Matched MatchmakingStatusStatus = "matched"
	Queued  MatchmakingStatusStatus = "queued"
)

// Valid indicates whether the value is a known member of the MatchmakingStatusStatus enum.
func (e MatchmakingStatusStatus) Valid() bool {
	switch e {
	case Matched:
		return true
	case Queued:
		return true
	default:
		return false
	}
}

// Defines values for ObjectAvailability.
const (
	Available   ObjectAvailability = "available"
	Unavailable ObjectAvailability = "unavailable"
)

// Valid indicates whether the value is a known member of the ObjectAvailability enum.
func (e ObjectAvailability) Valid() bool {
	switch e {
	case Available:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// Defines values for ObjectKind.
const (
	Canvas       ObjectKind = "canvas"
	Directory    ObjectKind = "directory"
	LighterStand ObjectKind = "lighter_stand"
	Pc           ObjectKind = "pc"
	Workspace    ObjectKind = "workspace"
)

// Valid indicates whether the value is a known member of the ObjectKind enum.
func (e ObjectKind) Valid() bool {
	switch e {
	case Canvas:
		return true
	case Directory:
		return true
	case LighterStand:
		return true
	case Pc:
		return true
	case Workspace:
		return true
	default:
		return false
	}
}

// Defines values for ObjectScope.
const (
	Personal ObjectScope = "personal"
	Shared   ObjectScope = "shared"
)

// Valid indicates whether the value is a known member of the ObjectScope enum.
func (e ObjectScope) Valid() bool {
	switch e {
	case Personal:
		return true
	case Shared:
		return true
	default:
		return false
	}
}

// Defines values for Outcome.
const (
	Defeat  Outcome = "defeat"
	Victory Outcome = "victory"
)

// Valid indicates whether the value is a known member of the Outcome enum.
func (e Outcome) Valid() bool {
	switch e {
	case Defeat:
		return true
	case Victory:
		return true
	default:
		return false
	}
}

// Defines values for PhaseStatus.
const (
	PhaseStatusActive       PhaseStatus = "active"
	PhaseStatusCompleted    PhaseStatus = "completed"
	PhaseStatusIntermission PhaseStatus = "intermission"
)

// Valid indicates whether the value is a known member of the PhaseStatus enum.
func (e PhaseStatus) Valid() bool {
	switch e {
	case PhaseStatusActive:
		return true
	case PhaseStatusCompleted:
		return true
	case PhaseStatusIntermission:
		return true
	default:
		return false
	}
}

// Defines values for PlayerKind.
const (
	Cpu   PlayerKind = "cpu"
	Human PlayerKind = "human"
)

// Valid indicates whether the value is a known member of the PlayerKind enum.
func (e PlayerKind) Valid() bool {
	switch e {
	case Cpu:
		return true
	case Human:
		return true
	default:
		return false
	}
}

// Defines values for SessionMode.
const (
	SessionModeMultiplayer SessionMode = "multiplayer"
	SessionModeSingle      SessionMode = "single"
)

// Valid indicates whether the value is a known member of the SessionMode enum.
func (e SessionMode) Valid() bool {
	switch e {
	case SessionModeMultiplayer:
		return true
	case SessionModeSingle:
		return true
	default:
		return false
	}
}

// Defines values for SessionSnapshotSchemaVersion.
const (
	N2 SessionSnapshotSchemaVersion = 2
)

// Valid indicates whether the value is a known member of the SessionSnapshotSchemaVersion enum.
func (e SessionSnapshotSchemaVersion) Valid() bool {
	switch e {
	case N2:
		return true
	default:
		return false
	}
}

// Defines values for SessionStatus.
const (
	SessionStatusFinished     SessionStatus = "finished"
	SessionStatusIntermission SessionStatus = "intermission"
	SessionStatusPlaying      SessionStatus = "playing"
	SessionStatusWaiting      SessionStatus = "waiting"
)

// Valid indicates whether the value is a known member of the SessionStatus enum.
func (e SessionStatus) Valid() bool {
	switch e {
	case SessionStatusFinished:
		return true
	case SessionStatusIntermission:
		return true
	case SessionStatusPlaying:
		return true
	case SessionStatusWaiting:
		return true
	default:
		return false
	}
}

// Defines values for TaskStatus.
const (
	TaskStatusCompleted TaskStatus = "completed"
	TaskStatusPending   TaskStatus = "pending"
)

// Valid indicates whether the value is a known member of the TaskStatus enum.
func (e TaskStatus) Valid() bool {
	switch e {
	case TaskStatusCompleted:
		return true
	case TaskStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for TaskType.
const (
	ImageGeneration TaskType = "image_generation"
	ReadEdit        TaskType = "read_edit"
	WebSearch       TaskType = "web_search"
	Write           TaskType = "write"
)

// Valid indicates whether the value is a known member of the TaskType enum.
func (e TaskType) Valid() bool {
	switch e {
	case ImageGeneration:
		return true
	case ReadEdit:
		return true
	case WebSearch:
		return true
	case Write:
		return true
	default:
		return false
	}
}

// Defines values for GetHealth200JSONResponseBodyStatus.
const (
	Ok GetHealth200JSONResponseBodyStatus = "ok"
)

// Valid indicates whether the value is a known member of the GetHealth200JSONResponseBodyStatus enum.
func (e GetHealth200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// ConnectionStatus defines model for ConnectionStatus.
type ConnectionStatus string

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	Mode CreateSessionRequestMode `json:"mode"`
}

// CreateSessionRequestMode defines model for CreateSessionRequest.Mode.
type CreateSessionRequestMode string

// Error defines model for Error.
type Error struct {
	// Code Example: not_found
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Game defines model for Game.
type Game struct {
	// Phase 開始前は null
	Phase *Phase `json:"phase"`

	// Result 決着前は null
	Result *Result `json:"result"`

	// Team チーム共有の勝利条件フラグ
	Team Team `json:"team"`
}

// GameObject ワールドに置かれた、機能を持つ物体
type GameObject struct {
	Availability ObjectAvailability `json:"availability"`

	// Data kind が directory なら DirectoryData。他は未定(null)
	Data *JsonValue `json:"data"`

	// Id Example: directory-1
	Id string `json:"id"`

	// Kind directory 以外は暫定の名前
	Kind ObjectKind `json:"kind"`

	// Owner scope が personal のときだけ
	Owner *PlayerId `json:"owner,omitempty"`

	// Position [x, y, z]。ワールド座標(Y-up)
	//
	// Example: [1.25,0,-2.5]
	Position Vec3 `json:"position"`

	// Scope personal は各プレイヤーの区画のもの。shared は全員共通(ディレクトリだけ)
	Scope ObjectScope `json:"scope"`

	// Users 今触っているプレイヤー。personal は最大 1 人、shared は複数人
	Users []PlayerId `json:"users"`
}

// Item 手に持つ物。手は 1 つなので、プレイヤーが持てるのは 1 個
type Item struct {
	// Data kind が file なら FileItemData、lighter なら null
	Data *JsonValue `json:"data"`

	// Id Example: file-02
	Id   string   `json:"id"`
	Kind ItemKind `json:"kind"`
}

// ItemKind defines model for ItemKind.
type ItemKind string

// JsonValue kind ごとに中身が決まる自由な JSON
type JsonValue = interface{}

// LifeStatus defines model for LifeStatus.
type LifeStatus string

// MatchmakingStatus defines model for MatchmakingStatus.
type MatchmakingStatus struct {
	QueuedAt time.Time `json:"queuedAt"`

	// SessionId status が matched のときだけ
	SessionId *string                 `json:"sessionId,omitempty"`
	Status    MatchmakingStatusStatus `json:"status"`
}

// MatchmakingStatusStatus defines model for MatchmakingStatus.Status.
type MatchmakingStatusStatus string

// Me defines model for Me.
type Me struct {
	// PlayerId Example: p1
	PlayerId PlayerId `json:"playerId"`

	// SessionId 参加中のセッション。無ければ null
	SessionId *string `json:"sessionId"`
}

// ObjectAvailability defines model for ObjectAvailability.
type ObjectAvailability string

// ObjectKind directory 以外は暫定の名前
type ObjectKind string

// ObjectScope personal は各プレイヤーの区画のもの。shared は全員共通(ディレクトリだけ)
type ObjectScope string

// Outcome defines model for Outcome.
type Outcome string

// Phase defines model for Phase.
type Phase struct {
	// DeadlineAt 残り時間はこれと serverTime から算出する
	DeadlineAt time.Time   `json:"deadlineAt"`
	Number     int         `json:"number"`
	StartedAt  time.Time   `json:"startedAt"`
	Status     PhaseStatus `json:"status"`
	Tasks      []Task      `json:"tasks"`
}

// PhaseStatus defines model for PhaseStatus.
type PhaseStatus string

// Player defines model for Player.
type Player struct {
	Connection ConnectionStatus `json:"connection"`
	HeldItem   *Item            `json:"heldItem"`
	Kind       PlayerKind       `json:"kind"`
	Life       LifeStatus       `json:"life"`

	// PlayerId Example: p1
	PlayerId PlayerId `json:"playerId"`

	// Seat サンドボックスの区画の番号
	Seat      int       `json:"seat"`
	Transform Transform `json:"transform"`
}

// PlayerId Example: p1
type PlayerId = string

// PlayerKind defines model for PlayerKind.
type PlayerKind string

// PlayerStatus transform を除くプレイヤー情報(player.updated で配る)
type PlayerStatus struct {
	Connection ConnectionStatus `json:"connection"`
	HeldItem   *Item            `json:"heldItem"`
	Kind       PlayerKind       `json:"kind"`
	Life       LifeStatus       `json:"life"`

	// PlayerId Example: p1
	PlayerId PlayerId `json:"playerId"`

	// Seat サンドボックスの区画の番号
	Seat int `json:"seat"`
}

// Result defines model for Result.
type Result struct {
	DecidedAt time.Time `json:"decidedAt"`
	Outcome   Outcome   `json:"outcome"`
}

// Seq セッション内の確定状態の更新順序。単調に増える
type Seq = int64

// SessionId Example: sess-abc123
type SessionId = string

// SessionMode defines model for SessionMode.
type SessionMode string

// SessionSnapshot defines model for SessionSnapshot.
type SessionSnapshot struct {
	CreatedAt     time.Time                    `json:"createdAt"`
	Game          Game                         `json:"game"`
	Mode          SessionMode                  `json:"mode"`
	Objects       []GameObject                 `json:"objects"`
	Players       []Player                     `json:"players"`
	SchemaVersion SessionSnapshotSchemaVersion `json:"schemaVersion"`

	// Seq セッション内の確定状態の更新順序。単調に増える
	Seq Seq `json:"seq"`

	// ServerTime 送信時のサーバー時刻。クライアントは時計のずれの補正に使う
	ServerTime time.Time `json:"serverTime"`

	// SessionId Example: sess-abc123
	SessionId SessionId     `json:"sessionId"`
	Status    SessionStatus `json:"status"`
}

// SessionSnapshotSchemaVersion defines model for SessionSnapshot.SchemaVersion.
type SessionSnapshotSchemaVersion int

// SessionStatus defines model for SessionStatus.
type SessionStatus string

// Task defines model for Task.
type Task struct {
	// AssigneePlayerId Example: p1
	AssigneePlayerId PlayerId `json:"assigneePlayerId"`

	// CompletedAt サーバーが完了を受け付けた時刻
	CompletedAt *time.Time `json:"completedAt"`
	Status      TaskStatus `json:"status"`

	// TargetFileId read_edit のときだけ。対象の在庫ファイルの id
	TargetFileId *string  `json:"targetFileId"`
	TaskId       string   `json:"taskId"`
	Type         TaskType `json:"type"`
}

// TaskStatus defines model for TaskStatus.
type TaskStatus string

// TaskType defines model for TaskType.
type TaskType string

// Team チーム共有の勝利条件フラグ
type Team struct {
	BypassPermission bool `json:"bypassPermission"`
	FireStarted      bool `json:"fireStarted"`
}

// Transform defines model for Transform.
type Transform struct {
	// Pitch ラジアン。上向きが正
	Pitch float64 `json:"pitch"`

	// Position 足元の位置
	Position Vec3 `json:"position"`

	// Seq そのプレイヤーの更新ごとに増やす。増えない更新は捨てる
	Seq int64 `json:"seq"`

	// Yaw ラジアン。0 で -Z を向く
	Yaw float64 `json:"yaw"`
}

// Vec3 [x, y, z]。ワールド座標(Y-up)
//
// Example: [1.25,0,-2.5]
type Vec3 = []float64

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GetHealth200JSONResponseBodyStatus defines parameters for GetHealth.
type GetHealth200JSONResponseBodyStatus string

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// LeaveMatchmaking 待機をやめる
	// (DELETE /api/v1/matchmaking)
	LeaveMatchmaking(w http.ResponseWriter, r *http.Request)
	// GetMatchmaking 自分のマッチング状況(ポーリング用)
	// (GET /api/v1/matchmaking)
	GetMatchmaking(w http.ResponseWriter, r *http.Request)
	// JoinMatchmaking 自動マッチングの待機列に入る
	// (POST /api/v1/matchmaking)
	JoinMatchmaking(w http.ResponseWriter, r *http.Request)
	// CreatePlayer 匿名プレイヤーを作り、Cookie を発行する
	// (POST /api/v1/players)
	CreatePlayer(w http.ResponseWriter, r *http.Request)
	// GetMe 自分の ID と、参加中のセッション
	// (GET /api/v1/players/me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// CreateSession シングルモードのセッションを作る
	// (POST /api/v1/sessions)
	CreateSession(w http.ResponseWriter, r *http.Request)
	// GetSession セッションのスナップショット(参加者のみ)
	// (GET /api/v1/sessions/{sessionId})
	GetSession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// ConnectSession WebSocket に切り替える(参加者のみ)
	// (GET /api/v1/sessions/{sessionId}/ws)
	ConnectSession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// GetHealth ヘルスチェック
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// LeaveMatchmaking operation middleware
func (siw *ServerInterfaceWrapper) LeaveMatchmaking(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LeaveMatchmaking(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMatchmaking operation middleware
func (siw *ServerInterfaceWrapper) GetMatchmaking(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMatchmaking(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// JoinMatchmaking operation middleware
func (siw *ServerInterfaceWrapper) JoinMatchmaking(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.JoinMatchmaking(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePlayer operation middleware
func (siw *ServerInterfaceWrapper) CreatePlayer(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePlayer(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConnectSession operation middleware
func (siw *ServerInterfaceWrapper) ConnectSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConnectSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/players", wrapper.CreatePlayer)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/players/me", wrapper.GetMe)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/matchmaking", wrapper.LeaveMatchmaking)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/matchmaking", wrapper.GetMatchmaking)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/matchmaking", wrapper.JoinMatchmaking)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/sessions", wrapper.CreateSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/sessions/{sessionId}", wrapper.GetSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/sessions/{sessionId}/ws", wrapper.ConnectSession)

	return m
}
