# typos(git hooks)の設定。https://github.com/crate-ci/typos/blob/master/docs/reference.md
[files]
# Go のモジュールのバージョンやハッシュを誤検出するため
extend-exclude = ["go.mod", "go.sum"]

[default.extend-words]
# PNG のフィルタ名(Paeth predictor)
Paeth = "Paeth"
