/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** ヘルスチェック */
    get: operations["getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/players": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 匿名プレイヤーを作り、Cookie を発行する
     * @description 既に有効な Cookie があれば、新しく作らずにそのプレイヤーを返す。
     */
    post: operations["createPlayer"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/players/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 自分の ID と、参加中のセッション */
    get: operations["getMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/wisp/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 実サイトへ出る WISP プロキシに繋ぐための、短い期限つきの URL を発行する
     * @description WISP は誰でも使えると、オープンプロキシになる。プレイヤーの Cookie がある人だけに、
     *     期限つきの署名トークンを付けた WebSocket の URL を返す。WISP 側はトークンを検証してから流す。
     */
    get: operations["getWispToken"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/matchmaking": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 自分のマッチング状況(ポーリング用) */
    get: operations["getMatchmaking"];
    put?: never;
    /**
     * 自動マッチングの待機列に入る
     * @description 既に待機中なら今の状況を返す。セッションに参加中なら 409。
     */
    post: operations["joinMatchmaking"];
    /** 待機をやめる */
    delete: operations["leaveMatchmaking"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * シングルモードのセッションを作る
     * @description マルチプレイのセッションは自動マッチングでのみ作られる。
     */
    post: operations["createSession"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sessions/{sessionId}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sessionId: components["parameters"]["SessionId"];
      };
      cookie?: never;
    };
    /** セッションのスナップショット(参加者のみ) */
    get: operations["getSession"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sessions/{sessionId}/ws": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sessionId: components["parameters"]["SessionId"];
      };
      cookie?: never;
    };
    /**
     * WebSocket に切り替える(参加者のみ)
     * @description 切り替え後、サーバーはまず `snapshot` を送る。以降のメッセージは
     *     `ClientMessage` / `ServerMessage` を参照。再接続も同じエンドポイントで行う。
     */
    get: operations["connectSession"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @example p1 */
    PlayerId: string;
    /** @example sess-abc123 */
    SessionId: string;
    /**
     * Format: int64
     * @description セッション内の確定状態の更新順序。単調に増える
     */
    Seq: number;
    /**
     * @description [x, y, z]。ワールド座標(Y-up)
     * @example [
     *       1.25,
     *       0,
     *       -2.5
     *     ]
     */
    Vec3: number[];
    /** @description kind ごとに中身が決まる自由な JSON(null を含む何でも) */
    JsonValue: unknown;
    Error: {
      /** @example not_found */
      code: string;
      message: string;
    };
    /** @enum {string} */
    SessionMode: "single" | "multiplayer";
    /** @enum {string} */
    SessionStatus: "waiting" | "playing" | "intermission" | "finished";
    /** @enum {string} */
    PlayerKind: "human" | "cpu";
    /** @enum {string} */
    ConnectionStatus: "connecting" | "connected" | "disconnected";
    /** @enum {string} */
    LifeStatus: "alive" | "eliminated";
    /** @enum {string} */
    PhaseStatus: "active" | "intermission" | "completed";
    /** @enum {string} */
    TaskType: "read_edit" | "write" | "web_search" | "image_generation";
    /** @enum {string} */
    TaskStatus: "pending" | "completed";
    /** @enum {string} */
    ItemKind: "file" | "lighter";
    /**
     * @description ファイルの状態。unedited / edited はディレクトリの在庫から取り出したもの。
     *     file_created / search_created / image_created は新しく作ったもの(編集はしない)
     * @enum {string}
     */
    FileStatus:
      | "unedited"
      | "edited"
      | "file_created"
      | "search_created"
      | "image_created";
    /**
     * @description 在庫のファイルの状態(編集前か編集済みか)
     * @enum {string}
     */
    StockFileStatus: "unedited" | "edited";
    /**
     * @description directory 以外は暫定の名前
     * @enum {string}
     */
    ObjectKind: "directory" | "workspace" | "canvas" | "pc" | "lighter_stand";
    /**
     * @description personal は各プレイヤーの区画のもの。shared は全員共通(ディレクトリだけ)
     * @enum {string}
     */
    ObjectScope: "personal" | "shared";
    /** @enum {string} */
    ObjectAvailability: "available" | "unavailable";
    /** @enum {string} */
    RejectReason:
      | "not_found"
      | "not_owner"
      | "unavailable"
      | "too_far"
      | "missing_item";
    /** @enum {string} */
    Outcome: "victory" | "defeat";
    Me: {
      playerId: components["schemas"]["PlayerId"];
      /** @description 参加中のセッション。無ければ null */
      sessionId: string | null;
    };
    WispToken: {
      /**
       * @description WISP の WebSocket の URL。`token` のクエリを含む
       * @example wss://example.test/wisp/?token=abc.def
       */
      url: string;
      /**
       * Format: date-time
       * @description トークンの期限(接続を始めるのはこの前に)
       */
      expiresAt: string;
    };
    MatchmakingStatus: {
      /** @enum {string} */
      status: "queued" | "matched";
      /** Format: date-time */
      queuedAt: string;
      /** @description status が matched のときだけ */
      sessionId?: string;
    };
    CreateSessionRequest: {
      /** @enum {string} */
      mode: "single";
    };
    /** @description 手に持つ物。手は 1 つなので、プレイヤーが持てるのは 1 個 */
    Item: {
      /** @example file-02 */
      id: string;
      kind: components["schemas"]["ItemKind"];
      /** @description kind が file なら FileItemData、lighter なら null */
      data: components["schemas"]["JsonValue"];
    };
    FileItemData: {
      status: components["schemas"]["FileStatus"];
      /**
       * @description アウトラインの色。在庫から取り出したファイルだけ持つ
       * @example #ffd60a
       */
      color?: string;
    };
    /** @description インタラクト時の手持ちの主張。識別に足りる分だけ */
    HeldItemRef: {
      id: string;
      kind: components["schemas"]["ItemKind"];
    };
    /** @description ワールドに置かれた、機能を持つ物体。位置はサーバーが持たず、フロントが id(personal なら owner の席)から決める */
    GameObject: {
      /** @example directory-1 */
      id: string;
      kind: components["schemas"]["ObjectKind"];
      scope: components["schemas"]["ObjectScope"];
      /** @description scope が personal のときだけ */
      owner?: components["schemas"]["PlayerId"];
      /** @description 今触っているプレイヤー。personal は最大 1 人、shared は複数人 */
      users: components["schemas"]["PlayerId"][];
      availability: components["schemas"]["ObjectAvailability"];
      /** @description kind が directory なら DirectoryData、lighter_stand なら LighterStandData。他は未定(null) */
      data: components["schemas"]["JsonValue"];
    };
    StockFile: {
      id: string;
      color: string;
      status: components["schemas"]["StockFileStatus"];
    };
    DirectoryData: {
      /** @description 今ディレクトリの中にある在庫のファイル(誰かが持っている間は含まれない) */
      stock: components["schemas"]["StockFile"][];
      /** @description このフェーズで入れられた成果物(新しく作ったファイル)の数 */
      outputs: number;
    };
    /** @description ライターの置き場。bypassPermission が立つまでは availability が unavailable */
    LighterStandData: {
      /** @description 置き場にライターがあるか(持ち主が持っている間は false) */
      hasLighter: boolean;
    };
    Transform: {
      /** @description 足元の位置 */
      position: components["schemas"]["Vec3"];
      /**
       * Format: double
       * @description ラジアン。0 で -Z を向く
       */
      yaw: number;
      /**
       * Format: double
       * @description ラジアン。上向きが正
       */
      pitch: number;
      /**
       * Format: int64
       * @description そのプレイヤーの更新ごとに増やす。増えない更新は捨てる
       */
      seq: number;
    };
    /** @description transform を除くプレイヤー情報(player.updated で配る) */
    PlayerStatus: {
      playerId: components["schemas"]["PlayerId"];
      kind: components["schemas"]["PlayerKind"];
      /** @description サンドボックスの区画の番号 */
      seat: number;
      connection: components["schemas"]["ConnectionStatus"];
      life: components["schemas"]["LifeStatus"];
      heldItem: components["schemas"]["Item"] | null;
    };
    Player: components["schemas"]["PlayerStatus"] & {
      /** @description 最初の transform を受け取るまでは null。初期位置はサーバーが持たず、フロントが seat から決める */
      transform: components["schemas"]["Transform"] | null;
    };
    Task: {
      taskId: string;
      type: components["schemas"]["TaskType"];
      assigneePlayerId: components["schemas"]["PlayerId"];
      /** @description read_edit のときだけ。対象の在庫ファイルの id */
      targetFileId: string | null;
      status: components["schemas"]["TaskStatus"];
      /**
       * Format: date-time
       * @description サーバーが完了を受け付けた時刻
       */
      completedAt: string | null;
    };
    Phase: {
      number: number;
      status: components["schemas"]["PhaseStatus"];
      /** Format: date-time */
      startedAt: string;
      /**
       * Format: date-time
       * @description 残り時間はこれと serverTime から算出する
       */
      deadlineAt: string;
      tasks: components["schemas"]["Task"][];
    };
    /** @description チーム共有の勝利条件フラグ */
    Team: {
      bypassPermission: boolean;
      fireStarted: boolean;
    };
    Result: {
      outcome: components["schemas"]["Outcome"];
      /** Format: date-time */
      decidedAt: string;
    };
    Game: {
      /** @description 開始前は null */
      phase: components["schemas"]["Phase"] | null;
      team: components["schemas"]["Team"];
      /** @description 決着前は null */
      result: components["schemas"]["Result"] | null;
    };
    SessionSnapshot: {
      /** @enum {integer} */
      schemaVersion: 2;
      sessionId: components["schemas"]["SessionId"];
      mode: components["schemas"]["SessionMode"];
      status: components["schemas"]["SessionStatus"];
      /** Format: date-time */
      createdAt: string;
      /**
       * Format: date-time
       * @description 送信時のサーバー時刻。クライアントは時計のずれの補正に使う
       */
      serverTime: string;
      seq: components["schemas"]["Seq"];
      players: components["schemas"]["Player"][];
      objects: components["schemas"]["GameObject"][];
      game: components["schemas"]["Game"];
    };
    ClientMessage:
      | components["schemas"]["TransformMessage"]
      | components["schemas"]["InteractMessage"];
    /** @description 自分の位置と向き。20Hz で送る(止まっている間は送らなくてよい) */
    TransformMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "transform";
      position: components["schemas"]["Vec3"];
      /** Format: double */
      yaw: number;
      /** Format: double */
      pitch: number;
      /** Format: int64 */
      seq: number;
    };
    /** @description オブジェクトへの操作の要求。送信者は接続から決まる */
    InteractMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "interact";
      objectId: string;
      /** @description 手持ちの主張(サーバーは実際の手持ちで判定する)。手ぶらなら null */
      heldItem: components["schemas"]["HeldItemRef"] | null;
      /** @description 対象の中から 1 つ選ぶときの指定(例: 取り出すファイルの id) */
      target?: string;
    };
    ServerMessage:
      | components["schemas"]["SnapshotMessage"]
      | components["schemas"]["TransformsMessage"]
      | components["schemas"]["SessionStartedMessage"]
      | components["schemas"]["SessionFinishedMessage"]
      | components["schemas"]["PhaseStartedMessage"]
      | components["schemas"]["PhaseEndedMessage"]
      | components["schemas"]["TaskCompletedMessage"]
      | components["schemas"]["ObjectUpsertMessage"]
      | components["schemas"]["ObjectRemoveMessage"]
      | components["schemas"]["InteractRejectedMessage"]
      | components["schemas"]["PlayerUpdatedMessage"]
      | components["schemas"]["TeamUpdatedMessage"]
      | components["schemas"]["EffectMessage"]
      | components["schemas"]["ErrorMessage"];
    /** @description 接続・再接続した本人に、最初に送る */
    SnapshotMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "snapshot";
      session: components["schemas"]["SessionSnapshot"];
    };
    /** @description 前回の配信から動いたプレイヤーの位置と向き。最大 20Hz で全員に送り、誰も動いていなければ送らない。seq を持たない */
    TransformsMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "transforms";
      /** Format: date-time */
      serverTime: string;
      players: {
        playerId: components["schemas"]["PlayerId"];
        transform: components["schemas"]["Transform"];
      }[];
    };
    SessionStartedMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "session.started";
      seq: components["schemas"]["Seq"];
      /** Format: date-time */
      startedAt: string;
    };
    SessionFinishedMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "session.finished";
      seq: components["schemas"]["Seq"];
      result: components["schemas"]["Result"];
    };
    PhaseStartedMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "phase.started";
      seq: components["schemas"]["Seq"];
      /** Format: date-time */
      serverTime: string;
      phase: components["schemas"]["Phase"];
    };
    PhaseEndedMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "phase.ended";
      seq: components["schemas"]["Seq"];
      phaseNumber: number;
      /** @description このフェーズの締切で脱落したプレイヤー */
      eliminatedPlayerIds: components["schemas"]["PlayerId"][];
      /**
       * @description intermission なら次のフェーズがある。completed なら最後のフェーズだった
       * @enum {string}
       */
      next: "intermission" | "completed";
    };
    TaskCompletedMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "task.completed";
      seq: components["schemas"]["Seq"];
      taskId: string;
      /** Format: date-time */
      completedAt: string;
    };
    ObjectUpsertMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "object.upsert";
      seq: components["schemas"]["Seq"];
      object: components["schemas"]["GameObject"];
    };
    ObjectRemoveMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "object.remove";
      seq: components["schemas"]["Seq"];
      id: string;
    };
    /** @description 要求した本人にだけ送る。画面上は何も起きない。seq を持たない */
    InteractRejectedMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "object.interactRejected";
      objectId: string;
      reason: components["schemas"]["RejectReason"];
    };
    /** @description 接続状態・生死・手持ちの変化 */
    PlayerUpdatedMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "player.updated";
      seq: components["schemas"]["Seq"];
      player: components["schemas"]["PlayerStatus"];
    };
    TeamUpdatedMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "team.updated";
      seq: components["schemas"]["Seq"];
      team: components["schemas"]["Team"];
    };
    /** @description 一時的な演出。確定状態ではなく、再接続時に再生しない。seq を持たない */
    EffectMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "effect";
      /** @enum {string} */
      name: "fall" | "fire" | "conflict";
      playerId?: components["schemas"]["PlayerId"];
      objectId?: string;
    };
    /** @description 不正なメッセージなど。本人にだけ送る */
    ErrorMessage: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "error";
      code: string;
      message: string;
    };
  };
  responses: {
    /** @description Cookie が無い、または無効 */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description セッションの参加者ではない */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description 見つからない */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description 今は使えない(設定が無いなど) */
    Unavailable: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description 今の状態ではできない(既にセッションに参加中など) */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: {
    SessionId: components["schemas"]["SessionId"];
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 稼働中 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @enum {string} */
            status: "ok";
          };
        };
      };
    };
  };
  createPlayer: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 既存のプレイヤー */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
      /** @description 新しく作ったプレイヤー */
      201: {
        headers: {
          /** @description `iubeo_player=<token>; HttpOnly; Secure; SameSite=Lax; Path=/` */
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 自分 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
      401: components["responses"]["Unauthorized"];
    };
  };
  getWispToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 接続先の URL(トークンを含む) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WispToken"];
        };
      };
      401: components["responses"]["Unauthorized"];
      503: components["responses"]["Unavailable"];
    };
  };
  getMatchmaking: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 待機状況 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MatchmakingStatus"];
        };
      };
      401: components["responses"]["Unauthorized"];
      404: components["responses"]["NotFound"];
    };
  };
  joinMatchmaking: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 待機状況 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MatchmakingStatus"];
        };
      };
      401: components["responses"]["Unauthorized"];
      409: components["responses"]["Conflict"];
    };
  };
  leaveMatchmaking: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 待機列から外れた */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      404: components["responses"]["NotFound"];
      /** @description 既にマッチングが成立している */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  createSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSessionRequest"];
      };
    };
    responses: {
      /** @description 作ったセッション */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionSnapshot"];
        };
      };
      401: components["responses"]["Unauthorized"];
      409: components["responses"]["Conflict"];
    };
  };
  getSession: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sessionId: components["parameters"]["SessionId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description スナップショット */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionSnapshot"];
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  connectSession: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sessionId: components["parameters"]["SessionId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description WebSocket に切り替えた */
      101: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
}
